[Database]
Usr = ""
Pwd = ""
DB = ""
Host = ""

[Paths]
LogFile = "/var/log/autobk/autobk-r.log"
BackupDir = "/var/autobk/backups"
ScriptDir = "/var/autobk/python"

[Tasks]
SleepDuration = 5
MaintenanceHz = 15
SchedulingHz = 50
AutoBackupsHz = 45

[Extensions]
APEX = "csv"
DCM = "tgz"
CAP = "zip"
Vista = "txt"
Inca1 = "bak"
OneNet = "zip"
OneNetLog = "txt"
TC600E = "xml"
CXCHP = "Backup"
PSSend = "json"
Quartet = "xcfg"
FakeDevice = "txt"
